### ISSUE TITLE
Open links next to current tab

### ISSUE THREAD

**Issue by gitdine** [Lepovirta/yahe#11]
When pressing ctrl+enter to open a link in a new tab, it would be preferable to open next to the current tab instead of at the end of the tab strip, as such behaviour is annoying when you have a lot of tabs open.

Thanks.

**Comment by jpallari** [comment]
Hey @gitdine! Thanks for the feedback.

The current behaviour is emulating the browser's "open in new tab" functionality. I'm not sure, if it's possible to control the tab placement from the extension, but I'll have a look just in case. If it is possible, I think I could make it an option. If you have any further insight into it, I'd be happy to hear about it.

**Comment by gitdine** [comment]
I'm not a developer so I'm not sure about the technical side, but I use an extension called [New Tab Beside](https://addons.mozilla.org/en-GB/firefox/addon/new-tab-beside/) that opens a new tab next to the current one and is activated by a hotkey -- that's why I thought it might be possible.

P.S. Thanks for the response and the extension!

**Comment by jpallari** [comment]
Leaving some notes for myself:
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/newTabPosition

**Comment by myfonj** [comment]
BTW, there is general `browser.tabs.insertAfterCurrent` about:config pref that when set to true makes tabs opening quite sane.
