### ISSUE TITLE
Incompatible with the Just Read extension

### ISSUE THREAD

**Issue by vfaronov** [Lepovirta/yahe#3]
YAHE doesn’t work on views generated by [Just Read](https://github.com/ZachSaucier/Just-Read), a rather popular readability extension for Chrome. See [ZachSaucier/Just-Read issue #164](https://github.com/ZachSaucier/Just-Read/issues/164) and [#29](https://github.com/ZachSaucier/Just-Read/issues/29). According to the author of Just Read, YAHE would need to add `"match_about_blank": true` to its manifest in order to work with Just Read. Would you like to do so? I’m not sure what the implications are.

**Comment by jpallari** [comment]
Hi @vfaronov! Thanks for investigating this. I'll have a look into. I'll check if the `match_about_blank` setting does the trick. Cheers!

**Comment by jpallari** [comment]
Hey @vfaronov. I've created a fix you requested (see PR #4), and briefly tested it with Just Read. It seems work great, but it'd be nice for other people to test it out before I release it. Could you test it, please?

Instructions:

- Clone this repo
- Checkout the branch `frame-support`
- Open <chrome://extensions> in Chrome
- Enable developer mode in top-right corner.
- Disable YAHE momentarily
- Click "Load unpacked" and select the directory where you cloned YAHE
- Test a few sites with Just Read. You can also try YAHE in sites that include frames to see how they work now.

**Comment by vfaronov** [comment]
Works great for me. Thank you!

**Comment by jpallari** [comment]
Awesome! I'll merge the PR and push an update to Chrome webstore probably tomorrow.
